spring.application.name=payment-service

notification.service.base-url=http://localhost:8084

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

payment.kafka.topic.payment-success=payment-success-topic